import dotenv from 'dotenv'
dotenv.config()

// TODO: do some processing on the env variables, include some sane defaults

interface Shape {
	key: string
	def: string // default value ('default' is a reserved keyword, so i used 'def')
	env: string
	validate?: (value: any) => boolean
}
const confSchema: Shape[] = [
	{
		key: 'port',
		def: '80',
		env: 'PORT',
	},
	{
		key: 'api_key',
		def: '',
		env: 'API_KEY',
		validate: (value) => typeof value === 'string' && value.length > 0,
	},
	{
		key: 'blocklist_root',
		def: '/data',
		env: 'BLOCKLIST_ROOT',
		validate: (value) => typeof value === 'string' && value.length > 0,
	},
	{
		key: 'block_type',
		def: 'hostname',
		env: 'BLOCK_TYPE',
	},
	{
		key: 'blocklist_header',
		def: 'generated by ezblocklist\n(https://github.com/reeseovine/ezblocklist)',
		env: 'BLOCKLIST_HEADER',
	},
]

interface Conf {
	[name: string]: string
}
let envConf: Conf = {}
for (var item of confSchema) {
	envConf[item.key] = (process.env[item.env] as string | undefined) || item.def
}

export default envConf
